project:
  type: website

website:
  description: "A blog built with Quarto"
  title: "Yura Jeong"
  site-url: https://yura0703.github.io
  navbar:
    left:
      - href: index.qmd
        text: CV
      - href: blog.qmd
        text: Blog
    right:
      - icon: github
        href: https://github.com/yura0703

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true